# Generated by Django 2.2.5 on 2019-09-28 21:05

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20190928_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
